"""
Alert model for ForenSOC detection and alerting.
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, func, INET
from sqlalchemy.orm import relationship
from app.models.base import BaseModel


class Alert(BaseModel):
    """Security alert generated by detection engine."""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    alert_number = Column(String(50), unique=True, nullable=False, index=True)
    
    # Content
    title = Column(String(255), nullable=False)
    description = Column(Text)
    
    # Severity & Status
    severity = Column(String(20), nullable=False, index=True)  # 'Low', 'Medium', 'High', 'Critical'
    status = Column(String(50), default="New", nullable=False, index=True)  # 'New', 'In Progress', 'Investigating', 'Closed', 'False Positive'
    alert_type = Column(String(100))  # 'SSH Brute Force', 'Port Scan', 'Ransomware', etc.
    
    # Network Context
    source_ip = Column(INET, nullable=True, index=True)
    dest_ip = Column(INET, nullable=True)
    source_port = Column(Integer, nullable=True)
    dest_port = Column(Integer, nullable=True)
    hostname = Column(String(255), nullable=True)
    username = Column(String(255), nullable=True)
    
    # Timeline
    event_time = Column(DateTime, nullable=True)
    detected_time = Column(DateTime, server_default=func.now(), nullable=False)
    closed_at = Column(DateTime, nullable=True)
    
    # MITRE ATT&CK
    mitre_tactic = Column(String(100), nullable=True)
    mitre_technique = Column(String(100), nullable=True)
    mitre_id = Column(String(20), nullable=True)  # 'T1110', 'T1046', etc.
    
    # Relationships
    raw_event_id = Column(Integer, ForeignKey("raw_events.id"), nullable=True)
    case_id = Column(Integer, ForeignKey("cases.id"), nullable=True, index=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    assigned_to = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    # Relationships
    raw_event = relationship("RawEvent")
    case = relationship("Case", back_populates="alerts")
    creator = relationship("User", foreign_keys=[created_by], back_populates="created_alerts")
    assigned_analyst = relationship("User", foreign_keys=[assigned_to], back_populates="assigned_alerts")
    notes = relationship("AlertNote", back_populates="alert", cascade="all, delete-orphan")
    timeline_events = relationship("TimelineEvent", back_populates="related_alert")
    mitre_mappings = relationship("MitreMapping", foreign_keys="MitreMapping.alert_id", back_populates="alert", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Alert {self.alert_number}: {self.title}>"


class AlertNote(BaseModel):
    """Analyst notes on an alert."""
    __tablename__ = "alert_notes"
    
    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(Integer, ForeignKey("alerts.id"), nullable=False, index=True)
    analyst_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    note_text = Column(Text, nullable=False)
    
    # Relationships
    alert = relationship("Alert", back_populates="notes")
    analyst = relationship("User")
    
    def __repr__(self):
        return f"<AlertNote for Alert {self.alert_id}>"
